# Generated by Django 5.1.5 on 2026-03-03 14:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_number', models.CharField(help_text='Court-assigned case number (e.g., CV-2024-900123).', max_length=50, unique=True)),
                ('internal_reference', models.CharField(blank=True, help_text="Firm's internal file/matter number.", max_length=50)),
                ('caption', models.CharField(help_text="Case caption, e.g., 'Smith v. Jones Properties LLC'.", max_length=255)),
                ('court', models.CharField(help_text="Full court name, e.g., 'Jefferson County Circuit Court'.", max_length=200)),
                ('county', models.CharField(help_text='Alabama county. Affects holiday calendar (Mardi Gras in Mobile/Baldwin).', max_length=50)),
                ('jurisdiction', models.CharField(choices=[('STATE', 'State'), ('FEDERAL', 'Federal')], default='STATE', max_length=10)),
                ('case_type', models.CharField(choices=[('PREMISES_LIABILITY', 'Premises Liability'), ('AUTO_ACCIDENT', 'Auto Accident'), ('PRODUCTS_LIABILITY', 'Products Liability'), ('MEDICAL_MALPRACTICE', 'Medical Malpractice'), ('GENERAL_LIABILITY', 'General Liability'), ('WORKERS_COMP', "Workers' Compensation"), ('OTHER', 'Other')], default='PREMISES_LIABILITY', max_length=25)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SETTLED', 'Settled'), ('DISMISSED', 'Dismissed'), ('CLOSED', 'Closed'), ('ON_APPEAL', 'On Appeal')], default='ACTIVE', max_length=15)),
                ('plaintiff_name', models.CharField(max_length=255)),
                ('defendant_name', models.CharField(help_text='Our client (the defendant we represent).', max_length=255)),
                ('date_filed', models.DateField(blank=True, null=True)),
                ('date_served', models.DateField(blank=True, help_text='Date defendant was served. Setting this triggers automatic deadline generation.', null=True)),
                ('service_method', models.CharField(blank=True, choices=[('PERSONAL', 'Personal Service'), ('CERTIFIED_MAIL', 'Certified Mail'), ('PUBLICATION', 'Service by Publication'), ('EFILE', 'E-File / E-Service'), ('PROCESS_SERVER', 'Process Server'), ('WAIVER', 'Waiver of Service')], max_length=20)),
                ('date_answer_due', models.DateField(blank=True, null=True)),
                ('date_closed', models.DateField(blank=True, null=True)),
                ('pled_contributory_negligence', models.BooleanField(default=False, help_text='Has contributory negligence been pled in the Answer? Alabama is a pure contributory negligence state — waived if not pled.')),
                ('pled_assumption_of_risk', models.BooleanField(default=False, help_text='Has assumption of risk been pled in the Answer?')),
                ('supervising_partner', models.CharField(default='Warren', max_length=100)),
                ('assigned_paralegal', models.CharField(default='Mary', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Brief case summary or notes.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CASE_CREATED', 'Case Created'), ('CASE_UPDATED', 'Case Updated'), ('CASE_CLOSED', 'Case Closed'), ('DEADLINE_CREATED', 'Deadline Created'), ('DEADLINE_COMPLETED', 'Deadline Completed'), ('DEADLINE_UPDATED', 'Deadline Updated'), ('DEADLINE_AUTO_GENERATED', 'Deadline Auto-Generated'), ('CONTACT_ADDED', 'Contact Added'), ('CONTACT_UPDATED', 'Contact Updated'), ('NOTE_ADDED', 'Note Added')], max_length=30)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_log', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(blank=True, help_text='Null for system-level events not tied to a specific case.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_log', to='cases.case')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CaseContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('PLAINTIFF_ATTORNEY', 'Plaintiff Attorney'), ('CO_DEFENDANT_ATTORNEY', 'Co-Defendant Attorney'), ('EXPERT_WITNESS', 'Expert Witness'), ('FACT_WITNESS', 'Fact Witness'), ('INSURANCE_ADJUSTER', 'Insurance Adjuster'), ('MEDIATOR', 'Mediator'), ('COURT_REPORTER', 'Court Reporter'), ('JUDGE', 'Judge'), ('CLERK', 'Clerk'), ('OTHER', 'Other')], default='OTHER', max_length=25)),
                ('firm', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='cases.case')),
            ],
            options={
                'ordering': ['role', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField(db_index=True)),
                ('completed', models.BooleanField(default=False)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('completion_notes', models.TextField(blank=True)),
                ('rule_reference', models.CharField(blank=True, help_text="Applicable rule, e.g., 'ARCP Rule 12(a)' or '28 U.S.C. 1446'.", max_length=100)),
                ('deadline_type', models.CharField(choices=[('ANSWER', 'Answer'), ('REMOVAL', 'Federal Removal'), ('DISCOVERY', 'Discovery'), ('MOTION', 'Motion'), ('TRIAL', 'Trial'), ('PRETRIAL', 'Pretrial'), ('MEDIATION', 'Mediation'), ('APPEAL', 'Appeal'), ('POST_JUDGMENT', 'Post-Judgment'), ('INTERNAL', 'Internal'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('is_extendable', models.BooleanField(default=True, help_text='False for jurisdictional deadlines that cannot be extended.')),
                ('is_jurisdictional', models.BooleanField(default=False, help_text='True if missing this deadline results in loss of jurisdiction.')),
                ('alert_days_before', models.PositiveIntegerField(default=7, help_text='Number of days before due_date to trigger a calendar alert.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='cases.case')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_deadlines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('note_type', models.CharField(choices=[('GENERAL', 'General'), ('RESEARCH', 'Research'), ('STRATEGY', 'Strategy'), ('CLIENT_COMMUNICATION', 'Client Communication'), ('COURT_FILING', 'Court Filing'), ('INTERNAL', 'Internal')], default='GENERAL', max_length=25)),
                ('is_privileged', models.BooleanField(default=False, help_text='Attorney-client privileged communication. Handle with care in discovery.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_notes', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='cases.case')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
