# Generated by Django 5.1.5 on 2026-03-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='claim_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='case',
            name='client_approved',
            field=models.BooleanField(default=False, help_text='Has the client/carrier approved the defense strategy?'),
        ),
        migrations.AddField(
            model_name='case',
            name='date_of_loss',
            field=models.DateField(blank=True, help_text='Date of the incident or accident.', null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='insurance_carrier',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='case',
            name='phase',
            field=models.CharField(choices=[('PLEADING', 'Pleading'), ('DISCOVERY', 'Discovery'), ('DISPOSITIVE_MOTIONS', 'Dispositive Motions'), ('TRIAL_PREP', 'Trial Preparation'), ('TRIAL', 'Trial'), ('POST_TRIAL', 'Post-Trial'), ('APPEAL', 'Appeal')], default='PLEADING', max_length=25),
        ),
        migrations.AddField(
            model_name='case',
            name='policy_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Policy limit in dollars.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='reserve_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Insurance reserve amount in dollars.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='short_name',
            field=models.CharField(blank=True, help_text="Short reference name, e.g., 'Smith premises'.", max_length=100),
        ),
        migrations.AddField(
            model_name='case',
            name='statute_of_limitations',
            field=models.DateField(blank=True, help_text='SOL expiry. Auto-calculated for premises liability (2 years from loss).', null=True),
        ),
        migrations.AddField(
            model_name='deadline',
            name='assigned_to',
            field=models.CharField(blank=True, help_text='Person responsible for this deadline.', max_length=100),
        ),
    ]
