# Generated by Django 5.1.5 on 2026-03-05 03:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_calendartoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangelogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(help_text="Semantic version string, e.g. '1.1.0'.", max_length=20, unique=True)),
                ('title', models.CharField(help_text="Short headline, e.g. 'Peach Pink Theme'.", max_length=200)),
                ('description', models.TextField(help_text='Plain-language summary written for Virginia, not dev notes.')),
                ('is_published', models.BooleanField(default=True, help_text='Unpublished entries are hidden from the changelog page.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'changelog entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserChangelogRead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_read_version', models.CharField(help_text='The version string the user last dismissed.', max_length=20)),
                ('last_read_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='changelog_read', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user changelog read',
                'verbose_name_plural': 'user changelog reads',
            },
        ),
    ]
