# Generated by Django 5.1.5 on 2026-03-05 03:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_initial_changelog_entry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('FEATURE', 'Feature Request'), ('BUG', 'Bug Report'), ('CHANGE', 'Change Request'), ('OTHER', 'Other')], default='FEATURE', help_text='What kind of request this is.', max_length=10)),
                ('title', models.CharField(help_text='Short summary of the request.', max_length=200)),
                ('description', models.TextField(help_text='The details in her own words.')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('REVIEWED', 'Reviewed'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done'), ('WONT_DO', "Won't Do")], default='NEW', max_length=15)),
                ('admin_notes', models.TextField(blank=True, help_text="Kasey's notes on what he did or why he won't do it.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When this request was marked done.', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
